application: jadshelloworld 
version: 4
runtime: python27
api_version: 1
threadsafe: yes
handlers:
- url: /static
  static_dir: static
  secure: always
  
- url: /wiki(.*)
  script: wiki.urls.app
  secure: always

- url: /blog(.*)
  script: blog.urls.app
  secure: always

- url: .*
  script: urls.app
  secure: always
  
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- .git
- .gitignore
- bin
- include
- share
- lib
- local
- build

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.1"
