application: jadshelloworld 
version: 3
runtime: python27
api_version: 1
threadsafe: yes
handlers:
- url: .*
  script: urls.app
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- .git
- .gitignore
- bin
- include
- share
- lib
- local
- build

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.1"
