application: jadshelloworld 
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: helloworld.app

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.1"
